#!/usr/bin/python

import dbus
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("set", help="{objectName}")
parser.add_argument("property", help="{propertyToSet}")
parser.add_argument("value", help="{value}")
parser.add_argument("valueType", help="{valueType}")
args = parser.parse_args()

objectName = args.set
propertyToSet = args.property
value = args.value
valueType = args.valueType

realValue = 0
if valueType == "boolean":
	realValue = bool(value)
elif valueType == "integer":
	realValue = int(value)


bus = dbus.SystemBus()
managerObject = bus.get_object("org.automotive.message.broker", "/");
managerInterface = dbus.Interface(managerObject, "org.automotive.Manager")

object = managerInterface.FindObjectForZone(objectName, 0)

propertiesInterface = dbus.Interface(bus.get_object("org.automotive.message.broker", object),"org.freedesktop.DBus.Properties")
print propertiesInterface.Set("org.automotive."+objectName, propertyToSet, realValue)
print "Success!"
