#!/bin/bash

BUTTONVALUE=$1

echo "Button pressed: ${BUTTONVALUE}"

if [[ ${BUTTONVALUE} = Right ]]
then
	gst-launch v4l2src device=/dev/video0 ! 'video/x-raw-yuv,width=1920,height=1080,framerate=30/1' ! xvimagesink
else
	if [[ ${BUTTONVALUE} = Left ]]
	then
		gst-launch v4l2src device=/dev/video1 ! 'video/x-raw-yuv,width=1920,height=1080,framerate=30/1' ! xvimagesink
	fi
fi

if [[ ${BUTTONVALUE} = Off ]]
then
	killall gst-launch-0.10
fi
