/*
 * Generated by gdbus-codegen 2.32.1. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "bluetoothmanagerproxy.h"

#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        ret = (g_value_get_double (a) == g_value_get_double (b));
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.bluez.Manager
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:OrgBluezManager
 * @title: OrgBluezManager
 * @short_description: Generated C code for the org.bluez.Manager D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-bluez-Manager.top_of_page">org.bluez.Manager</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.bluez.Manager ---- */

static const _ExtendedGDBusArgInfo _org_bluez_manager_method_info_get_properties_OUT_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_method_info_get_properties_OUT_ARG_pointers[] =
{
  &_org_bluez_manager_method_info_get_properties_OUT_ARG_unnamed_arg0,
  NULL
};

static const GDBusAnnotationInfo _org_bluez_manager_method_get_properties_annotation_info_0 =
{
  -1,
  "com.trolltech.QtDBus.QtTypeName.Out0",
  "QVariantMap",
  NULL
};

static const GDBusAnnotationInfo * const _org_bluez_manager_method_get_properties_annotation_info_pointers[] =
{
  &_org_bluez_manager_method_get_properties_annotation_info_0,
  NULL
};

static const _ExtendedGDBusMethodInfo _org_bluez_manager_method_info_get_properties =
{
  {
    -1,
    "GetProperties",
    NULL,
    (GDBusArgInfo **) &_org_bluez_manager_method_info_get_properties_OUT_ARG_pointers,
    (GDBusAnnotationInfo **) &_org_bluez_manager_method_get_properties_annotation_info_pointers
  },
  "handle-get-properties",
  FALSE
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_method_info_default_adapter_OUT_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_method_info_default_adapter_OUT_ARG_pointers[] =
{
  &_org_bluez_manager_method_info_default_adapter_OUT_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _org_bluez_manager_method_info_default_adapter =
{
  {
    -1,
    "DefaultAdapter",
    NULL,
    (GDBusArgInfo **) &_org_bluez_manager_method_info_default_adapter_OUT_ARG_pointers,
    NULL
  },
  "handle-default-adapter",
  FALSE
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_method_info_find_adapter_IN_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_method_info_find_adapter_IN_ARG_pointers[] =
{
  &_org_bluez_manager_method_info_find_adapter_IN_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_method_info_find_adapter_OUT_ARG_unnamed_arg1 =
{
  {
    -1,
    "unnamed_arg1",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_method_info_find_adapter_OUT_ARG_pointers[] =
{
  &_org_bluez_manager_method_info_find_adapter_OUT_ARG_unnamed_arg1,
  NULL
};

static const _ExtendedGDBusMethodInfo _org_bluez_manager_method_info_find_adapter =
{
  {
    -1,
    "FindAdapter",
    (GDBusArgInfo **) &_org_bluez_manager_method_info_find_adapter_IN_ARG_pointers,
    (GDBusArgInfo **) &_org_bluez_manager_method_info_find_adapter_OUT_ARG_pointers,
    NULL
  },
  "handle-find-adapter",
  FALSE
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_method_info_list_adapters_OUT_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "ao",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_method_info_list_adapters_OUT_ARG_pointers[] =
{
  &_org_bluez_manager_method_info_list_adapters_OUT_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusMethodInfo _org_bluez_manager_method_info_list_adapters =
{
  {
    -1,
    "ListAdapters",
    NULL,
    (GDBusArgInfo **) &_org_bluez_manager_method_info_list_adapters_OUT_ARG_pointers,
    NULL
  },
  "handle-list-adapters",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _org_bluez_manager_method_info_pointers[] =
{
  &_org_bluez_manager_method_info_get_properties,
  &_org_bluez_manager_method_info_default_adapter,
  &_org_bluez_manager_method_info_find_adapter,
  &_org_bluez_manager_method_info_list_adapters,
  NULL
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_signal_info_property_changed_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_signal_info_property_changed_ARG_unnamed_arg1 =
{
  {
    -1,
    "unnamed_arg1",
    "v",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_signal_info_property_changed_ARG_pointers[] =
{
  &_org_bluez_manager_signal_info_property_changed_ARG_unnamed_arg0,
  &_org_bluez_manager_signal_info_property_changed_ARG_unnamed_arg1,
  NULL
};

static const _ExtendedGDBusSignalInfo _org_bluez_manager_signal_info_property_changed =
{
  {
    -1,
    "PropertyChanged",
    (GDBusArgInfo **) &_org_bluez_manager_signal_info_property_changed_ARG_pointers,
    NULL
  },
  "property-changed"
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_signal_info_adapter_added_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_signal_info_adapter_added_ARG_pointers[] =
{
  &_org_bluez_manager_signal_info_adapter_added_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusSignalInfo _org_bluez_manager_signal_info_adapter_added =
{
  {
    -1,
    "AdapterAdded",
    (GDBusArgInfo **) &_org_bluez_manager_signal_info_adapter_added_ARG_pointers,
    NULL
  },
  "adapter-added"
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_signal_info_adapter_removed_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_signal_info_adapter_removed_ARG_pointers[] =
{
  &_org_bluez_manager_signal_info_adapter_removed_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusSignalInfo _org_bluez_manager_signal_info_adapter_removed =
{
  {
    -1,
    "AdapterRemoved",
    (GDBusArgInfo **) &_org_bluez_manager_signal_info_adapter_removed_ARG_pointers,
    NULL
  },
  "adapter-removed"
};

static const _ExtendedGDBusArgInfo _org_bluez_manager_signal_info_default_adapter_changed_ARG_unnamed_arg0 =
{
  {
    -1,
    "unnamed_arg0",
    "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _org_bluez_manager_signal_info_default_adapter_changed_ARG_pointers[] =
{
  &_org_bluez_manager_signal_info_default_adapter_changed_ARG_unnamed_arg0,
  NULL
};

static const _ExtendedGDBusSignalInfo _org_bluez_manager_signal_info_default_adapter_changed =
{
  {
    -1,
    "DefaultAdapterChanged",
    (GDBusArgInfo **) &_org_bluez_manager_signal_info_default_adapter_changed_ARG_pointers,
    NULL
  },
  "default-adapter-changed"
};

static const _ExtendedGDBusSignalInfo * const _org_bluez_manager_signal_info_pointers[] =
{
  &_org_bluez_manager_signal_info_property_changed,
  &_org_bluez_manager_signal_info_adapter_added,
  &_org_bluez_manager_signal_info_adapter_removed,
  &_org_bluez_manager_signal_info_default_adapter_changed,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _org_bluez_manager_interface_info =
{
  {
    -1,
    "org.bluez.Manager",
    (GDBusMethodInfo **) &_org_bluez_manager_method_info_pointers,
    (GDBusSignalInfo **) &_org_bluez_manager_signal_info_pointers,
    NULL,
    NULL
  },
  "org-bluez-manager",
};


/**
 * org_bluez_manager_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-bluez-Manager.top_of_page">org.bluez.Manager</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
org_bluez_manager_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_org_bluez_manager_interface_info;
}

/**
 * org_bluez_manager_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #OrgBluezManager interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
org_bluez_manager_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * OrgBluezManager:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-bluez-Manager.top_of_page">org.bluez.Manager</link>.
 */

/**
 * OrgBluezManagerIface:
 * @parent_iface: The parent interface.
 * @handle_default_adapter: Handler for the #OrgBluezManager::handle-default-adapter signal.
 * @handle_find_adapter: Handler for the #OrgBluezManager::handle-find-adapter signal.
 * @handle_get_properties: Handler for the #OrgBluezManager::handle-get-properties signal.
 * @handle_list_adapters: Handler for the #OrgBluezManager::handle-list-adapters signal.
 * @adapter_added: Handler for the #OrgBluezManager::adapter-added signal.
 * @adapter_removed: Handler for the #OrgBluezManager::adapter-removed signal.
 * @default_adapter_changed: Handler for the #OrgBluezManager::default-adapter-changed signal.
 * @property_changed: Handler for the #OrgBluezManager::property-changed signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-bluez-Manager.top_of_page">org.bluez.Manager</link>.
 */

static void
org_bluez_manager_default_init (OrgBluezManagerIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * OrgBluezManager::handle-get-properties:
   * @object: A #OrgBluezManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-Manager.GetProperties">GetProperties()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call org_bluez_manager_complete_get_properties() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-properties",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezManagerIface, handle_get_properties),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * OrgBluezManager::handle-default-adapter:
   * @object: A #OrgBluezManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-Manager.DefaultAdapter">DefaultAdapter()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call org_bluez_manager_complete_default_adapter() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-default-adapter",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezManagerIface, handle_default_adapter),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * OrgBluezManager::handle-find-adapter:
   * @object: A #OrgBluezManager.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_unnamed_arg0: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-Manager.FindAdapter">FindAdapter()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call org_bluez_manager_complete_find_adapter() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-find-adapter",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezManagerIface, handle_find_adapter),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

  /**
   * OrgBluezManager::handle-list-adapters:
   * @object: A #OrgBluezManager.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-bluez-Manager.ListAdapters">ListAdapters()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call org_bluez_manager_complete_list_adapters() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-list-adapters",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezManagerIface, handle_list_adapters),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /* GObject signals for received D-Bus signals: */
  /**
   * OrgBluezManager::property-changed:
   * @object: A #OrgBluezManager.
   * @arg_unnamed_arg0: Argument.
   * @arg_unnamed_arg1: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-bluez-Manager.PropertyChanged">"PropertyChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("property-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezManagerIface, property_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    2, G_TYPE_STRING, G_TYPE_VARIANT);

  /**
   * OrgBluezManager::adapter-added:
   * @object: A #OrgBluezManager.
   * @arg_unnamed_arg0: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-bluez-Manager.AdapterAdded">"AdapterAdded"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("adapter-added",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezManagerIface, adapter_added),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * OrgBluezManager::adapter-removed:
   * @object: A #OrgBluezManager.
   * @arg_unnamed_arg0: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-bluez-Manager.AdapterRemoved">"AdapterRemoved"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("adapter-removed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezManagerIface, adapter_removed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

  /**
   * OrgBluezManager::default-adapter-changed:
   * @object: A #OrgBluezManager.
   * @arg_unnamed_arg0: Argument.
   *
   * On the client-side, this signal is emitted whenever the D-Bus signal <link linkend="gdbus-signal-org-bluez-Manager.DefaultAdapterChanged">"DefaultAdapterChanged"</link> is received.
   *
   * On the service-side, this signal can be used with e.g. g_signal_emit_by_name() to make the object emit the D-Bus signal.
   */
  g_signal_new ("default-adapter-changed",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (OrgBluezManagerIface, default_adapter_changed),
    NULL,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_NONE,
    1, G_TYPE_STRING);

}

typedef OrgBluezManagerIface OrgBluezManagerInterface;
G_DEFINE_INTERFACE (OrgBluezManager, org_bluez_manager, G_TYPE_OBJECT);

/**
 * org_bluez_manager_emit_property_changed:
 * @object: A #OrgBluezManager.
 * @arg_unnamed_arg0: Argument to pass with the signal.
 * @arg_unnamed_arg1: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-bluez-Manager.PropertyChanged">"PropertyChanged"</link> D-Bus signal.
 */
void
org_bluez_manager_emit_property_changed (
    OrgBluezManager *object,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1)
{
  g_signal_emit_by_name (object, "property-changed", arg_unnamed_arg0, arg_unnamed_arg1);
}

/**
 * org_bluez_manager_emit_adapter_added:
 * @object: A #OrgBluezManager.
 * @arg_unnamed_arg0: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-bluez-Manager.AdapterAdded">"AdapterAdded"</link> D-Bus signal.
 */
void
org_bluez_manager_emit_adapter_added (
    OrgBluezManager *object,
    const gchar *arg_unnamed_arg0)
{
  g_signal_emit_by_name (object, "adapter-added", arg_unnamed_arg0);
}

/**
 * org_bluez_manager_emit_adapter_removed:
 * @object: A #OrgBluezManager.
 * @arg_unnamed_arg0: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-bluez-Manager.AdapterRemoved">"AdapterRemoved"</link> D-Bus signal.
 */
void
org_bluez_manager_emit_adapter_removed (
    OrgBluezManager *object,
    const gchar *arg_unnamed_arg0)
{
  g_signal_emit_by_name (object, "adapter-removed", arg_unnamed_arg0);
}

/**
 * org_bluez_manager_emit_default_adapter_changed:
 * @object: A #OrgBluezManager.
 * @arg_unnamed_arg0: Argument to pass with the signal.
 *
 * Emits the <link linkend="gdbus-signal-org-bluez-Manager.DefaultAdapterChanged">"DefaultAdapterChanged"</link> D-Bus signal.
 */
void
org_bluez_manager_emit_default_adapter_changed (
    OrgBluezManager *object,
    const gchar *arg_unnamed_arg0)
{
  g_signal_emit_by_name (object, "default-adapter-changed", arg_unnamed_arg0);
}

/**
 * org_bluez_manager_call_get_properties:
 * @proxy: A #OrgBluezManagerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-Manager.GetProperties">GetProperties()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_manager_call_get_properties_finish() to get the result of the operation.
 *
 * See org_bluez_manager_call_get_properties_sync() for the synchronous, blocking version of this method.
 */
void
org_bluez_manager_call_get_properties (
    OrgBluezManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetProperties",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * org_bluez_manager_call_get_properties_finish:
 * @proxy: A #OrgBluezManagerProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_manager_call_get_properties().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with org_bluez_manager_call_get_properties().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_manager_call_get_properties_finish (
    OrgBluezManager *proxy,
    GVariant **out_unnamed_arg0,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a{sv})",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_manager_call_get_properties_sync:
 * @proxy: A #OrgBluezManagerProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-Manager.GetProperties">GetProperties()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See org_bluez_manager_call_get_properties() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_manager_call_get_properties_sync (
    OrgBluezManager *proxy,
    GVariant **out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetProperties",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(@a{sv})",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_manager_call_default_adapter:
 * @proxy: A #OrgBluezManagerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-Manager.DefaultAdapter">DefaultAdapter()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_manager_call_default_adapter_finish() to get the result of the operation.
 *
 * See org_bluez_manager_call_default_adapter_sync() for the synchronous, blocking version of this method.
 */
void
org_bluez_manager_call_default_adapter (
    OrgBluezManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "DefaultAdapter",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * org_bluez_manager_call_default_adapter_finish:
 * @proxy: A #OrgBluezManagerProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_manager_call_default_adapter().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with org_bluez_manager_call_default_adapter().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_manager_call_default_adapter_finish (
    OrgBluezManager *proxy,
    gchar **out_unnamed_arg0,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_manager_call_default_adapter_sync:
 * @proxy: A #OrgBluezManagerProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-Manager.DefaultAdapter">DefaultAdapter()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See org_bluez_manager_call_default_adapter() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_manager_call_default_adapter_sync (
    OrgBluezManager *proxy,
    gchar **out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "DefaultAdapter",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_manager_call_find_adapter:
 * @proxy: A #OrgBluezManagerProxy.
 * @arg_unnamed_arg0: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-Manager.FindAdapter">FindAdapter()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_manager_call_find_adapter_finish() to get the result of the operation.
 *
 * See org_bluez_manager_call_find_adapter_sync() for the synchronous, blocking version of this method.
 */
void
org_bluez_manager_call_find_adapter (
    OrgBluezManager *proxy,
    const gchar *arg_unnamed_arg0,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "FindAdapter",
    g_variant_new ("(s)",
                   arg_unnamed_arg0),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * org_bluez_manager_call_find_adapter_finish:
 * @proxy: A #OrgBluezManagerProxy.
 * @out_unnamed_arg1: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_manager_call_find_adapter().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with org_bluez_manager_call_find_adapter().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_manager_call_find_adapter_finish (
    OrgBluezManager *proxy,
    gchar **out_unnamed_arg1,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_unnamed_arg1);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_manager_call_find_adapter_sync:
 * @proxy: A #OrgBluezManagerProxy.
 * @arg_unnamed_arg0: Argument to pass with the method invocation.
 * @out_unnamed_arg1: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-Manager.FindAdapter">FindAdapter()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See org_bluez_manager_call_find_adapter() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_manager_call_find_adapter_sync (
    OrgBluezManager *proxy,
    const gchar *arg_unnamed_arg0,
    gchar **out_unnamed_arg1,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "FindAdapter",
    g_variant_new ("(s)",
                   arg_unnamed_arg0),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_unnamed_arg1);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_manager_call_list_adapters:
 * @proxy: A #OrgBluezManagerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-bluez-Manager.ListAdapters">ListAdapters()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_manager_call_list_adapters_finish() to get the result of the operation.
 *
 * See org_bluez_manager_call_list_adapters_sync() for the synchronous, blocking version of this method.
 */
void
org_bluez_manager_call_list_adapters (
    OrgBluezManager *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "ListAdapters",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * org_bluez_manager_call_list_adapters_finish:
 * @proxy: A #OrgBluezManagerProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_manager_call_list_adapters().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with org_bluez_manager_call_list_adapters().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_manager_call_list_adapters_finish (
    OrgBluezManager *proxy,
    gchar ***out_unnamed_arg0,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^ao)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_manager_call_list_adapters_sync:
 * @proxy: A #OrgBluezManagerProxy.
 * @out_unnamed_arg0: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-bluez-Manager.ListAdapters">ListAdapters()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See org_bluez_manager_call_list_adapters() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
org_bluez_manager_call_list_adapters_sync (
    OrgBluezManager *proxy,
    gchar ***out_unnamed_arg0,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "ListAdapters",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(^ao)",
                 out_unnamed_arg0);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * org_bluez_manager_complete_get_properties:
 * @object: A #OrgBluezManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg0: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-Manager.GetProperties">GetProperties()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
org_bluez_manager_complete_get_properties (
    OrgBluezManager *object,
    GDBusMethodInvocation *invocation,
    GVariant *unnamed_arg0)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(@a{sv})",
                   unnamed_arg0));
}

/**
 * org_bluez_manager_complete_default_adapter:
 * @object: A #OrgBluezManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg0: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-Manager.DefaultAdapter">DefaultAdapter()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
org_bluez_manager_complete_default_adapter (
    OrgBluezManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *unnamed_arg0)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   unnamed_arg0));
}

/**
 * org_bluez_manager_complete_find_adapter:
 * @object: A #OrgBluezManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg1: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-Manager.FindAdapter">FindAdapter()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
org_bluez_manager_complete_find_adapter (
    OrgBluezManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *unnamed_arg1)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   unnamed_arg1));
}

/**
 * org_bluez_manager_complete_list_adapters:
 * @object: A #OrgBluezManager.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @unnamed_arg0: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-bluez-Manager.ListAdapters">ListAdapters()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
org_bluez_manager_complete_list_adapters (
    OrgBluezManager *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *unnamed_arg0)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(^ao)",
                   unnamed_arg0));
}

/* ------------------------------------------------------------------------ */

/**
 * OrgBluezManagerProxy:
 *
 * The #OrgBluezManagerProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OrgBluezManagerProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OrgBluezManagerProxy.
 */

struct _OrgBluezManagerProxyPrivate
{
  GData *qdata;
};

static void org_bluez_manager_proxy_iface_init (OrgBluezManagerIface *iface);

G_DEFINE_TYPE_WITH_CODE (OrgBluezManagerProxy, org_bluez_manager_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_BLUEZ_MANAGER, org_bluez_manager_proxy_iface_init));

static void
org_bluez_manager_proxy_finalize (GObject *object)
{
  OrgBluezManagerProxy *proxy = ORG_BLUEZ_MANAGER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (org_bluez_manager_proxy_parent_class)->finalize (object);
}

static void
org_bluez_manager_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
org_bluez_manager_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
org_bluez_manager_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_org_bluez_manager_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_ORG_BLUEZ_MANAGER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_ORG_BLUEZ_MANAGER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
org_bluez_manager_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  OrgBluezManagerProxy *proxy = ORG_BLUEZ_MANAGER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_bluez_manager_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_bluez_manager_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
org_bluez_manager_proxy_init (OrgBluezManagerProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_ORG_BLUEZ_MANAGER_PROXY, OrgBluezManagerProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), org_bluez_manager_interface_info ());
}

static void
org_bluez_manager_proxy_class_init (OrgBluezManagerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (OrgBluezManagerProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = org_bluez_manager_proxy_finalize;
  gobject_class->get_property = org_bluez_manager_proxy_get_property;
  gobject_class->set_property = org_bluez_manager_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = org_bluez_manager_proxy_g_signal;
  proxy_class->g_properties_changed = org_bluez_manager_proxy_g_properties_changed;

}

static void
org_bluez_manager_proxy_iface_init (OrgBluezManagerIface *iface)
{
}

/**
 * org_bluez_manager_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-bluez-Manager.top_of_page">org.bluez.Manager</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_manager_proxy_new_finish() to get the result of the operation.
 *
 * See org_bluez_manager_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
org_bluez_manager_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_ORG_BLUEZ_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.bluez.Manager", NULL);
}

/**
 * org_bluez_manager_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_manager_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with org_bluez_manager_proxy_new().
 *
 * Returns: (transfer full) (type OrgBluezManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
OrgBluezManager *
org_bluez_manager_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return ORG_BLUEZ_MANAGER (ret);
  else
    return NULL;
}

/**
 * org_bluez_manager_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-bluez-Manager.top_of_page">org.bluez.Manager</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See org_bluez_manager_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OrgBluezManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
OrgBluezManager *
org_bluez_manager_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_ORG_BLUEZ_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.bluez.Manager", NULL);
  if (ret != NULL)
    return ORG_BLUEZ_MANAGER (ret);
  else
    return NULL;
}


/**
 * org_bluez_manager_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like org_bluez_manager_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call org_bluez_manager_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See org_bluez_manager_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
org_bluez_manager_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_ORG_BLUEZ_MANAGER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.bluez.Manager", NULL);
}

/**
 * org_bluez_manager_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to org_bluez_manager_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with org_bluez_manager_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type OrgBluezManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
OrgBluezManager *
org_bluez_manager_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return ORG_BLUEZ_MANAGER (ret);
  else
    return NULL;
}

/**
 * org_bluez_manager_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like org_bluez_manager_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See org_bluez_manager_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type OrgBluezManagerProxy): The constructed proxy object or %NULL if @error is set.
 */
OrgBluezManager *
org_bluez_manager_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_ORG_BLUEZ_MANAGER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.bluez.Manager", NULL);
  if (ret != NULL)
    return ORG_BLUEZ_MANAGER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * OrgBluezManagerSkeleton:
 *
 * The #OrgBluezManagerSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * OrgBluezManagerSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #OrgBluezManagerSkeleton.
 */

struct _OrgBluezManagerSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_org_bluez_manager_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_ORG_BLUEZ_MANAGER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_ORG_BLUEZ_MANAGER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_org_bluez_manager_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_bluez_manager_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_org_bluez_manager_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_org_bluez_manager_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _org_bluez_manager_skeleton_vtable =
{
  _org_bluez_manager_skeleton_handle_method_call,
  _org_bluez_manager_skeleton_handle_get_property,
  _org_bluez_manager_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
org_bluez_manager_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return org_bluez_manager_interface_info ();
}

static GDBusInterfaceVTable *
org_bluez_manager_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_org_bluez_manager_skeleton_vtable;
}

static GVariant *
org_bluez_manager_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_org_bluez_manager_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _org_bluez_manager_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _org_bluez_manager_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _org_bluez_manager_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.bluez.Manager", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
org_bluez_manager_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void
_org_bluez_manager_on_signal_property_changed (
    OrgBluezManager *object,
    const gchar *arg_unnamed_arg0,
    GVariant *arg_unnamed_arg1)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(s@v)",
                   arg_unnamed_arg0,
                   arg_unnamed_arg1));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.bluez.Manager", "PropertyChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_org_bluez_manager_on_signal_adapter_added (
    OrgBluezManager *object,
    const gchar *arg_unnamed_arg0)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_unnamed_arg0));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.bluez.Manager", "AdapterAdded",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_org_bluez_manager_on_signal_adapter_removed (
    OrgBluezManager *object,
    const gchar *arg_unnamed_arg0)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_unnamed_arg0));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.bluez.Manager", "AdapterRemoved",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void
_org_bluez_manager_on_signal_default_adapter_changed (
    OrgBluezManager *object,
    const gchar *arg_unnamed_arg0)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (object);

  GList      *connections, *l;
  GVariant   *signal_variant;
  connections = g_dbus_interface_skeleton_get_connections (G_DBUS_INTERFACE_SKELETON (skeleton));

  signal_variant = g_variant_ref_sink (g_variant_new ("(o)",
                   arg_unnamed_arg0));
  for (l = connections; l != NULL; l = l->next)
    {
      GDBusConnection *connection = l->data;
      g_dbus_connection_emit_signal (connection,
        NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.bluez.Manager", "DefaultAdapterChanged",
        signal_variant, NULL);
    }
  g_variant_unref (signal_variant);
  g_list_free_full (connections, g_object_unref);
}

static void org_bluez_manager_skeleton_iface_init (OrgBluezManagerIface *iface);
G_DEFINE_TYPE_WITH_CODE (OrgBluezManagerSkeleton, org_bluez_manager_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_ORG_BLUEZ_MANAGER, org_bluez_manager_skeleton_iface_init));

static void
org_bluez_manager_skeleton_finalize (GObject *object)
{
  OrgBluezManagerSkeleton *skeleton = ORG_BLUEZ_MANAGER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (org_bluez_manager_skeleton_parent_class)->finalize (object);
}

static void
org_bluez_manager_skeleton_init (OrgBluezManagerSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_ORG_BLUEZ_MANAGER_SKELETON, OrgBluezManagerSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
org_bluez_manager_skeleton_class_init (OrgBluezManagerSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (OrgBluezManagerSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = org_bluez_manager_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = org_bluez_manager_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = org_bluez_manager_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = org_bluez_manager_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = org_bluez_manager_skeleton_dbus_interface_get_vtable;
}

static void
org_bluez_manager_skeleton_iface_init (OrgBluezManagerIface *iface)
{
  iface->property_changed = _org_bluez_manager_on_signal_property_changed;
  iface->adapter_added = _org_bluez_manager_on_signal_adapter_added;
  iface->adapter_removed = _org_bluez_manager_on_signal_adapter_removed;
  iface->default_adapter_changed = _org_bluez_manager_on_signal_default_adapter_changed;
}

/**
 * org_bluez_manager_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-bluez-Manager.top_of_page">org.bluez.Manager</link>.
 *
 * Returns: (transfer full) (type OrgBluezManagerSkeleton): The skeleton object.
 */
OrgBluezManager *
org_bluez_manager_skeleton_new (void)
{
  return ORG_BLUEZ_MANAGER (g_object_new (TYPE_ORG_BLUEZ_MANAGER_SKELETON, NULL));
}

